// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvngrlvmyjwmmcywmavs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2bmdybHZteWp3bW1jeXdtYXZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNzAxODMsImV4cCI6MjA2MDk0NjE4M30.rp9QTp2l_bD8XtjlcTWBPbx7TF_-ko_T9477YTPN0Q4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);